#' create_config
#'
#' Generates (user generated) config.yaml files for unit tests. Use
#' \code{add_read()} and \code{add_write()} functions to add read and write
#' blocks.
#'
#' @param init_yaml full path of yaml file generated by `fair init`
#' @param path full path of config yaml file to be created (will be created
#' in the same directory as `init_yaml`)
#' @param description description field
#' @param script script field
#' @param force if `TRUE`, then if config.yaml file already exists, it will be
#' overwritten
#'
#' @export
#'
create_config <- function(init_yaml,
                          path,
                          description,
                          script,
                          force = TRUE) {

  # Read in init yaml file
  init <- configr::read.config(init_yaml)

  # Generate run_metadata block
  run_metadata <- list(default_input_namespace = init$namespaces$input,
                       default_output_namespace = init$namespaces$output,
                       description = description,
                       local_data_registry_url = init$registries$local$uri,
                       local_repo = init$git$local_repo,
                       remote_data_registry_url = init$registries$origin$uri,
                       script = script,
                       write_data_store = init$registries$local$data_store)

  # Check whether file already exists
  if (file.exists(path)) {
    if (force) {
      file.remove(path)
    } else {
      usethis::ui_stop(paste(usethis::ui_field(path), "already exists"))
    }
  }

  # If directory doesn't exist, create it
  directory <- dirname(path)
  if (!dir.exists(directory))
    dir.create(directory, recursive = TRUE)

  # Write working config.yaml file
  yaml::write_yaml(list(run_metadata = run_metadata), file = path)

  invisible(path)
}
