# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  push:
    branches: main
  pull_request:
    branches: main

name: test-coverage

jobs:
  test-coverage:
     # If the commit message isn't [skip ci]
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: covr

      - name: Install local registry
        run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Start registry
        run: $HOME/.fair/registry/scripts/start_fair_registry

      - name: Install R API
        run: Rscript -e 'remotes::install_local(upgrade = "never")'

      - name: init
        run: |
          rDataPipeline::fair_init(
            name = "Sonia Mitchell",
            identifier = "https://orcid.org/0000-0003-1536-2066",
            endpoint = "http://localhost:8000/api/")
        shell: Rscript {0}
      - name: Test coverage
        env:
          _RUN_TESTS_: true
        run: covr::codecov()
        shell: Rscript {0}
