on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - uses: sinoru/actions-setup-keychain@v1.0

      - name: Install system requirements (MacOS)
        if: runner.os == 'macOS'
        run : |
              rm '/usr/local/bin/gfortran'
              brew install hdf5
              brew install gdal
              
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install r dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Add credentials in keychain
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "\
          protocol=https
          host=github.com
          username=Personal Access Token
          password=$GITHUB_TOKEN" | git credential-osxkeychain store
          
      - name: Test coverage
        env:
          SCRC_API_TOKEN: ${{ secrets.SCRC_API_TOKEN }}
          RUN_TEST: "TRUE"
        run: |
          covr::codecov()
        shell: Rscript {0}
