# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Install R API system requirements (ubuntu-20.04)
        if: matrix.config.os == 'ubuntu-20.04'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')
        shell: bash
      - name: Install local registry
        run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Start registry
        run: $HOME/.fair/registry/scripts/start_fair_registry

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
