# run on all branches push or pull_request
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

name: test-coverage

jobs:
  test-coverage:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    # use matrix to define os and r version
    runs-on: ${{ matrix.config.os }}
    # use GITHUB_TOKEN as enviromental version for all steps
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      # set to run on macOS-latest and r release
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
    steps:
      # checkout
      - uses: actions/checkout@v2
      # Setup r
      - uses: r-lib/actions/setup-r@master
      # setup pandoc
      - uses: r-lib/actions/setup-pandoc@master
      # setup keychain needed to cache github token for upload_toml_to_github test
      - uses: sinoru/actions-setup-keychain@v1.0

      # install MacOS requirements
      - name: Install system requirements (MacOS)
        if: runner.os == 'macOS'
        run : |
              rm '/usr/local/bin/gfortran'
              brew install hdf5
              brew install gdal

      # store r dependencies so they can be cached
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      # Cache dependencies
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      # install r dependencies
      - name: Install r dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      # add github Personal Access Token to keychain
      # needed for upload_toml_to_github test
      # echos to git credential-osxkeychain
      # this emulate stdin() line by line
      - name: Add credentials in keychain
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "\
          protocol=https
          host=github.com
          username=Personal Access Token
          password=$GITHUB_TOKEN" | git credential-osxkeychain store

      # Run code coverage with RUN_TEST to enable upload_toml_to_github test
      - name: Test coverage
        env:
          SCRC_API_TOKEN: ${{ secrets.SCRC_API_TOKEN }}
          RUN_TEST: "TRUE"
        run: |
          covr::codecov()
        shell: Rscript {0}
